name: collision test
run-name: collision test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compliation
        run: sudo make
      - name: Test
        run: |
          make tests -j8
